### ISSUE TITLE
PATH environment for binary of softether

### ISSUE THREAD

**Issue by roumano** [softasap/sa-vpn-softether#3]
One option missing for this role is to update PATH environment with {{softether_home}}

personally i have added this small task to do this 
```
- name: "add {{softether_home}} to path"
  lineinfile:
    dest: /etc/profile.d/softether.sh
    state: present
    create: yes
    regexp: '^export PATH'
    line: 'export PATH=$PATH:{{softether_home}}'
```

**Comment by Voronenko** [comment]
Are you talking about use case for "client" use or "server" use ?

Because on server I just have softether service up, and connect to it mostly via openVPN native software.

**Comment by Voronenko** [comment]
i.e. you can submit PR, but in
defaults/main.yml  introduce 

```YAML
option_add_to_path=false
```

and than 

```YAML
- name: SoftEther | Add {{softether_home}} to path
  lineinfile:
    dest: /etc/profile.d/softether.sh
    state: present
    create: yes
    regexp: '^export PATH'
    line: 'export PATH=$PATH:{{softether_home}}'
  become: yes
  when: option_add_to_path
  tags:
    - softether
```
