### ISSUE TITLE
Set a administrator password

### ISSUE THREAD

**Issue by roumano** [softasap/sa-vpn-softether#5]
Hi,

I have modify the templates/scenarios/create_hub to eventually set a administrator password :   
```
{% if softether_master_password is defined %}
ServerPasswordSet {{softether_master_password}}
{% endif %}
```
It's working well on the first deployment

But it's failed on next deployment on task "Proceed with setup"
as it's type ./vpncmd localhost /server /IN:{{softether_init_script}}
and it's should be : 
./vpncmd localhost /server /IN:{{softether_init_script}} /PASSWORD:{{softether_master_password|default("")}}
( with the |default("") it's also working when it's not set a password

my temporary workarround is to stop the service before deploy
but it's not a fix ...

We can replace then " - name: SoftEther | Proceed with setup"
with
```
shell: ./vpncmd localhost /server /IN:{{softether_init_script}} /PASSWORD:{{softether_master_password|default("")}}
```
but it's will failed on the first deployment as it's not yet a password set

So i'm not sure how we can handle it ...
a idea ?

**Comment by Voronenko** [comment]
We need to perform detection, whenever instance was already initialized or this is first run

i.e. create some detection dummy script
```yaml
shell: ./vpncmd localhost /server /IN:{{softether_detection_script}} /PASSWORD:{{softether_master_password}}
ignore_errors: true
register: softether_detection
```

and analyze softether_detection.stdout for hints,  or, perhaps - this command will just return non zero on failure due to incorrect password.

than we can use later
when:  softether_detection | failed

...
